<a href="https://colab.research.google.com/github/raultyv/Tareas/blob/main/03_estructuras_de_datos_parte2_LAB.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img src="https://www.ctic.uni.edu.pe/wp-content/uploads/2022/04/588px-x-348px-web-1.png" alt="HTML5 Icon" width="900" height="350" >


<h1 align=center><font size = 5>ESTRUCTURAS DE DATOS - PARTE 2
</font></h1>

---


**Tabla de Contenidos**

- Diccionarios
- Sets
- Matrices

---

## 1. Diccionarios

**Concepto:**

Un diccionario es una estructura de datos que almacena pares clave-valor. Las claves deben ser únicas y se utilizan para acceder a los valores asociados.

### Ejemplo 1.1: Creación de Diccionarios y Acceso a Elementos


In [ ]:
# Crear un diccionario
persona = {'nombre': 'Ana', 'edad': 30, 'ciudad': 'Lima'}
print(persona)

In [ ]:
# Acceder a un valor
print("Nombre:", persona['nombre'])
print("Ciudad:", persona.get('ciudad'))


In [ ]:

# Añadir un nuevo par clave-valor
persona['profesion'] = 'Ingeniera'
print(persona)



In [ ]:
# Eliminar un par clave-valor
del persona['ciudad']
print(persona)

### Ejemplo 1.2: Métodos Útiles de Diccionarios


In [ ]:
# Obtener todas las claves
print(persona.keys())


In [ ]:
# Obtener todos los valores
print(persona.values())


In [ ]:
# Comprobar si una clave existe en el diccionario
if 'edad' in persona:
    print("La clave 'edad' está en el diccionario.")


### Ejercicio 1: Trabajando con Diccionarios

- Crea un diccionario que contenga información sobre un automóvil (marca, modelo, año, color).
- Accede a cada valor usando su clave.
- Añade una clave para el precio del automóvil.
- Elimina la clave del color del automóvil y muestra el diccionario actualizado.
- Usa keys() y values() para imprimir las claves y valores del diccionario.



## 2. Sets

Los sets son colecciones de elementos únicos y desordenados. Son útiles para eliminar duplicados o realizar operaciones matemáticas como intersección y unión.

### Ejemplo 2.1: Creación y Modificación de Sets

In [ ]:
# Crear un set
numeros = {1, 2, 3, 4, 5}
print(numeros)


In [ ]:
# Añadir elementos
numeros.add(6)
print(numeros)


In [ ]:
# Eliminar un elemento
numeros.remove(3)
print(numeros)


### Ejemplo 2.2: Operaciones de Conjuntos


In [ ]:
# Crear otro set
otro_set = {4, 5, 6, 7}

In [ ]:
# Unión de sets (todos los elementos)
union = numeros.union(otro_set)
print("Unión:", union)


In [ ]:
# Intersección de sets (elementos comunes)
interseccion = numeros.intersection(otro_set)
print("Intersección:", interseccion)


### Ejercicio 2: Operaciones con Sets

- Crea dos sets de números: uno con números del 1 al 10 y otro con números del 5 al 15.
- Encuentra la intersección y unión de ambos sets.
- Elimina un número del primer set.
- Usa un set para almacenar los nombres de tus amigos. Asegúrate de que no haya duplicados.

## 3. Matrices

En Python, las matrices pueden representarse como listas de listas. Para manipular matrices más avanzadas y realizar cálculos eficientes, utilizamos la librería NumPy.

### Ejemplo 3.1: Matrices con Listas de Listas


In [7]:
# Crear una matriz 3x3 con listas anidadas
matriz = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
print(matriz)


[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [12]:
# Acceder a elementos de la matriz
print("Elemento en [1][0]:", matriz[2][2])


Elemento en [1][0]: 9


In [3]:
# Modificar un elemento
matriz[2][0] = 10
print(matriz)

[[1, 2, 3], [4, 5, 6], [10, 8, 9]]


### Ejemplo 3.2: Manipulación de Matrices con NumPy


In [13]:
import numpy as np

# Crear una matriz 3x3 con NumPy
matriz_np = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print(matriz_np)




[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [16]:
my_array=np.array([[[1,2,3],[4,5,6],[7,8,9]],
                   [[10,20,30],[40,50,60],[70,80,90]]])
print(my_array)
my_array.shape

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 20 30]
  [40 50 60]
  [70 80 90]]]


(2, 3, 3)

In [5]:
# Sumar 10 a cada elemento
print(matriz_np + 10)



[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [17]:
# Multiplicar cada elemento por 2
print(matriz_np * 2)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


### Ejercicio 3: Operaciones con Matrices

- Crea una matriz 3x3 usando listas de listas.
- Modifica un valor de la matriz y muestra la matriz actualizada.
- Usa NumPy para crear una matriz 4x4 con números aleatorios enteros.
- Realiza una operación de suma con la matriz (suma 5 a cada elemento).
- Multiplica los elementos de la matriz por 2 usando NumPy.

In [25]:
matriz=[[2,4,5],[5,6,8],[18,24,31]]
print(matriz) #pregunta 1

matriz[2][0] = 0
print(matriz) #pregunta 2

import numpy as np
matriz_aleatoria = np.random.randint(0, 10, size=(4, 4)) # Números entre 0 y 10
#np.random.rand(4,4) numeros aleatorios dist normal
print(matriz_aleatoria) #pregunta 3

print(matriz_aleatoria + 5) #pregunta 4

print(matriz_aleatoria * 2) #pregunta 5

[[2, 4, 5], [5, 6, 8], [18, 24, 31]]
[[2, 4, 5], [5, 6, 8], [0, 24, 31]]
[[1 2 3 6]
 [0 0 2 3]
 [0 5 2 1]
 [9 0 3 5]]
[[ 6  7  8 11]
 [ 5  5  7  8]
 [ 5 10  7  6]
 [14  5  8 10]]
[[ 2  4  6 12]
 [ 0  0  4  6]
 [ 0 10  4  2]
 [18  0  6 10]]


## 4. Desafío


Eres el encargado de un almacén de productos electrónicos. Tienes un registro de ventas semanales para teléfonos, laptops y tabletas. Necesitas analizar las ventas para mejorar la gestión.

- Crea tres listas: una para teléfonos, otra para laptops y otra para tabletas con las ventas de cada día durante una semana.
- Usa slicing para obtener las ventas de los últimos 3 días de cada producto.
- Usa listas por comprensión para calcular el total de ventas de cada producto y el promedio de ventas diarias.
- Clasifica los productos en "ventas altas" o "ventas bajas" según si el promedio de ventas es mayor o menor a 5.

Instrucciones:
Usa sum() y len() para calcular el total de ventas y el promedio.
Clasifica las ventas usando listas por comprensión.

---

# Gracias por completar este laboratorio!

---